# Book settings
project:
  type: book
  output-dir: docs

book:
  title: "AWK cookbook"
  author: "Nina Dombrowski"
  logo: images/tree_of_life.png
  chapters:
    - index.qmd
    - code/1_Basics.qmd
    - code/Math.qmd
    - code/Dealing_with_seqs.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-overflow: wrap
  pdf:
    documentclass: scrreprt
    geometry:
      - top=4mm
      - left=4mm
    #  - textwidth=4.5in
      - heightrounded
    fontfamily: libertinus
    highlight-style: github
    pandoc_args: --listings
    includes:
      in_header: preamble.tex
    colorlinks: true
    #code-block-bg: 7FB3D5

execute:
  eval: false

knitr:
  opts_chunk:
    collapse: true
